[package]
name = "cargo-deadlinks"
description = "Cargo subcommand for checking your documentation for broken links"
version = "0.4.1"
authors = ["Maximilian Goisser <goisser94@gmail.com>"]

repository = "https://github.com/deadlinks/cargo-deadlinks"
homepage = "https://github.com/deadlinks/cargo-deadlinks"
readme = "README.md"

license = "MIT OR Apache-2.0"

[dependencies]
cargo_metadata = "0.8"
docopt = "1"
env_logger = "0.7"
html5ever = "0.24"
log = "0.4"
num_cpus = "1.8"
rayon = "1.0"
reqwest = { version = "0.10", features = ["blocking"] }
serde = "1.0"
serde_derive = "1.0"
url = "2"
walkdir = "2.1"

clippy = { version = "0.0.186", optional = true }
serde_json = "1.0.34"

[features]
default = []
unstable = [] # For travis-cargo.

travis = []
lint = ["clippy"]

[dev-dependencies]
assert_cmd = "0.11.0"
predicates = "1.0.0"
